CREATE SEQUENCE SEQ_BOARD;

CREATE TABLE TBL_BOARD(
	BNO NUMBER(10) PRIMARY KEY,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(2000) NOT NULL,
	WRITER VARCHAR2(1000) NOT NULL,
	REGDATE DATE DEFAULT SYSDATE,
	UPDATEDATE DATE DEFAULT SYSDATE
);

INSERT INTO TBL_BOARD
(BNO, TITLE, CONTENT, WRITER, REGDATE, UPDATEDATE)
VALUES(SEQ_BOARD.NEXTVAL, '하나다', '댕청이', 'user11', SYSDATE, SYSDATE
);

SELECT * FROM TBL_BOARD ;

INSERT INTO TBL_BOARD (BNO, TITLE, CONTENT, WRITER, REGDATE, UPDATEDATE) SELECT SEQ_BOARD.NEXTVAL, TITLE, CONTENT, WRITER, REGDATE , UPDATEDATE FROM TBL_BOARD;


TRUNCATE TABLE TBL_BOARD;


SELECT /*+ INDEX_DESC(TBL_BOARD, SYS_C007001)*/
BNO, TITLE, CONTENT, WRITER, REGDATE, UPDATEDATE
 FROM TBL_BOARD;

SELECT LAST_NUMBER FROM USER_SEQUENCES WHERE SEQUENCE_NAME=;


BEGIN
  FOR i IN 1..30 LOOP
    INSERT INTO TBL_BOARD
    (BNO, TITLE, CONTENT, WRITER, REGDATE, UPDATEDATE)
    VALUES
    (SEQ_BOARD.NEXTVAL, 
     '제목 ' || TO_CHAR(i), -- 각 레코드의 제목을 '제목 1', '제목 2'와 같이 생성
     '내용 ' || TO_CHAR(i), -- 각 레코드의 내용을 '내용 1', '내용 2'와 같이 생성
     'user' || TO_CHAR(DBMS_RANDOM.VALUE(1, 20)), -- user1부터 user20 중에서 랜덤하게 선택
     TO_TIMESTAMP(SYSDATE - DBMS_RANDOM.VALUE(1, 365), 'YYYY-MM-DD HH24:MI:SS'), -- 최근 1년 내에서 랜덤한 날짜 생성
     SYSTIMESTAMP -- 현재 시간으로 갱신
    );
  END LOOP;
  COMMIT;
END;










