CREATE TABLE TBL_FILE(
	UUID VARCHAR2(1000) CONSTRAINT PK_FILE PRIMARY KEY,
	UPLOAD_PATH VARCHAR2(1000),
	FILE_NAME VARCHAR2(1000),
	FILE_TYPE CHAR(1),
	BNO NUMBER(10),
	CONSTRAINT FK_FILE FOREIGN KEY(BNO) REFERENCES TBL_BOARD(BNO)
);

SELECT * FROM TBL_FILE;